<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Error' => 'Fehler',
    'Internal Server Error' => 'Interner Serverfehler',
    'Page not found' => 'Seite wurde nicht gefunden',
    'Parent' => 'Parent',
    'Parent entry "{entry}" is not a menu item' => 'Parent-Eintrag "{entry}" wird nicht im Menü angezeigt',
    'Permission denied' => 'Zugriff verweigert',
    'Please get in touch with {email}' => 'Bitte wenden Sie sich an {email}',
    'Show in menu' => 'Im Menü anzeigen',
    'The requested page was not found' => 'Die angeforderte Seite konnte nicht gefunden werden',
    'URL' => 'URL',
];
