<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '1 hour' => '',
    '15 minutes' => '',
    '30 minutes' => '',
    '5 minutes' => '',
    'API Endpoint' => '',
    'Accounts' => '',
    'All Instagram data related to your account {id} has been successfully removed.' => '',
    'An error occurred while refreshing the Instagram access token of {name}.' => '',
    'Are you sure you want to reset this Instagram account?' => '',
    'Click on "Preview Media" to check that the content is loaded correctly.' => '',
    'Copy link' => '',
    'Delete account' => '',
    'Disabled' => '',
    'Error' => 'Fehler',
    'Instafeed Error – {name}' => '',
    'Instagram' => '',
    'Instagram Account' => '',
    'Instagram Account Preview' => '',
    'Instagram Accounts' => '',
    'Instagram Connected' => '',
    'Instagram Data Removed' => '',
    'Instagram account "{name}" is linked to this account and the feed available via API endpoint {endpoint}.' => '',
    'Instagram account was added.' => '',
    'Instagram is not linked to this account yet. Connect it by clicking the link below:' => '',
    'Last refreshed' => '',
    'New Account' => '',
    'New Instagram Account' => '',
    'Preview media' => '',
    'Refresh token' => '',
    'Request caching' => '',
    'Show login link' => '',
    'This is a preview of the results returned by API endpoint {url}.' => '',
    'Unlink account' => '',
    'Update Account' => '',
    'Valid until' => '',
    'View account' => '',
    'You can now close this window.' => '',
    'Your Instagram account {name} has been successfully connected.' => '',
];
